# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'form.ui'
##
## Created by: Qt User Interface Compiler version 6.9.3
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWidgets import (QAbstractItemView, QAbstractSpinBox, QApplication, QCheckBox,
    QComboBox, QDoubleSpinBox, QFrame, QGroupBox,
    QHeaderView, QLCDNumber, QLabel, QMainWindow,
    QMenu, QMenuBar, QPushButton, QRadioButton,
    QScrollBar, QSizePolicy, QSlider, QSpinBox,
    QStackedWidget, QStatusBar, QTabWidget, QTableView,
    QTextBrowser, QTextEdit, QToolButton, QWidget)

from pyqtgraph import PlotWidget
from vtkmodules.qt.QVTKRenderWindowInteractor import QVTKRenderWindowInteractor

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1719, 850)
        MainWindow.setCursor(QCursor(Qt.CursorShape.SizeVerCursor))
        MainWindow.setMouseTracking(True)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setDocumentMode(True)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.tabWidget = QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName(u"tabWidget")
        self.tabWidget.setEnabled(True)
        self.tabWidget.setGeometry(QRect(10, 0, 1661, 861))
        self.tabWidget.setMouseTracking(False)
        self.tabWidget.setStyleSheet(u"")
        self.PreSurgery = QWidget()
        self.PreSurgery.setObjectName(u"PreSurgery")
        self.graphicsView_2 = QVTKRenderWindowInteractor(self.PreSurgery)
        self.graphicsView_2.setObjectName(u"graphicsView_2")
        self.graphicsView_2.setGeometry(QRect(260, 330, 421, 241))
        self.graphicsView_2.setStyleSheet(u"background-color: rgb(200, 177, 176);")
        self.toolbar = QTabWidget(self.PreSurgery)
        self.toolbar.setObjectName(u"toolbar")
        self.toolbar.setEnabled(True)
        self.toolbar.setGeometry(QRect(10, 40, 231, 451))
        self.toolbar.setIconSize(QSize(18, 23))
        self.File = QWidget()
        self.File.setObjectName(u"File")
        self.File.setAutoFillBackground(True)
        self.groupBox_8 = QGroupBox(self.File)
        self.groupBox_8.setObjectName(u"groupBox_8")
        self.groupBox_8.setGeometry(QRect(20, 130, 191, 181))
        self.label_7 = QLabel(self.groupBox_8)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(10, 10, 111, 16))
        font = QFont()
        font.setPointSize(10)
        self.label_7.setFont(font)
        self.label_9 = QLabel(self.groupBox_8)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(10, 80, 111, 16))
        self.label_9.setFont(font)
        self.pushButton_reset = QPushButton(self.groupBox_8)
        self.pushButton_reset.setObjectName(u"pushButton_reset")
        self.pushButton_reset.setGeometry(QRect(10, 140, 75, 24))
        self.pushButton_auto = QPushButton(self.groupBox_8)
        self.pushButton_auto.setObjectName(u"pushButton_auto")
        self.pushButton_auto.setGeometry(QRect(100, 140, 75, 24))
        self.display_window = QLCDNumber(self.groupBox_8)
        self.display_window.setObjectName(u"display_window")
        self.display_window.setGeometry(QRect(140, 0, 41, 31))
        self.display_window.setMaximumSize(QSize(16777215, 100))
        self.display_window.setAutoFillBackground(False)
        self.display_window.setStyleSheet(u"color: rgb(0, 0, 0); background-color: white;")
        self.display_level = QLCDNumber(self.groupBox_8)
        self.display_level.setObjectName(u"display_level")
        self.display_level.setGeometry(QRect(140, 70, 41, 31))
        self.display_level.setMaximumSize(QSize(16777215, 100))
        self.display_level.setAutoFillBackground(False)
        self.display_level.setStyleSheet(u"color: rgb(0, 0, 0); background-color: white;")
        self.changeContrast = QSlider(self.groupBox_8)
        self.changeContrast.setObjectName(u"changeContrast")
        self.changeContrast.setGeometry(QRect(20, 40, 151, 22))
        self.changeContrast.setStyleSheet(u"")
        self.changeContrast.setMaximum(99)
        self.changeContrast.setSingleStep(1)
        self.changeContrast.setPageStep(10)
        self.changeContrast.setValue(0)
        self.changeContrast.setOrientation(Qt.Orientation.Horizontal)
        self.changeBrightness = QSlider(self.groupBox_8)
        self.changeBrightness.setObjectName(u"changeBrightness")
        self.changeBrightness.setGeometry(QRect(20, 110, 151, 22))
        self.changeBrightness.setMaximum(99)
        self.changeBrightness.setSingleStep(1)
        self.changeBrightness.setPageStep(10)
        self.changeBrightness.setValue(0)
        self.changeBrightness.setOrientation(Qt.Orientation.Horizontal)
        self.toolButton_LoadFile = QToolButton(self.File)
        self.toolButton_LoadFile.setObjectName(u"toolButton_LoadFile")
        self.toolButton_LoadFile.setGeometry(QRect(40, 20, 61, 61))
        self.toolButton_LoadFile.setToolTipDuration(0)
        icon = QIcon(QIcon.fromTheme(QIcon.ThemeIcon.DocumentOpen))
        self.toolButton_LoadFile.setIcon(icon)
        self.toolButton_LoadFile.setIconSize(QSize(30, 30))
        self.toolButton_ExportFile = QToolButton(self.File)
        self.toolButton_ExportFile.setObjectName(u"toolButton_ExportFile")
        self.toolButton_ExportFile.setEnabled(False)
        self.toolButton_ExportFile.setGeometry(QRect(120, 20, 61, 61))
        self.toolButton_ExportFile.setToolTipDuration(0)
        icon1 = QIcon(QIcon.fromTheme(QIcon.ThemeIcon.DocumentSaveAs))
        self.toolButton_ExportFile.setIcon(icon1)
        self.toolButton_ExportFile.setIconSize(QSize(34, 34))
        icon2 = QIcon(QIcon.fromTheme(QIcon.ThemeIcon.DocumentPageSetup))
        self.toolbar.addTab(self.File, icon2, "")
        self.tab = QWidget()
        self.tab.setObjectName(u"tab")
        self.stackedWidget = QStackedWidget(self.tab)
        self.stackedWidget.setObjectName(u"stackedWidget")
        self.stackedWidget.setEnabled(True)
        self.stackedWidget.setGeometry(QRect(0, 20, 221, 401))
        self.page = QWidget()
        self.page.setObjectName(u"page")
        self.checkBox_threshold = QCheckBox(self.page)
        self.checkBox_threshold.setObjectName(u"checkBox_threshold")
        self.checkBox_threshold.setEnabled(True)
        self.checkBox_threshold.setGeometry(QRect(60, 70, 101, 20))
        self.checkBox_threshold.setChecked(True)
        self.frame_6 = QFrame(self.page)
        self.frame_6.setObjectName(u"frame_6")
        self.frame_6.setGeometry(QRect(20, 100, 191, 241))
        self.frame_6.setFrameShape(QFrame.Shape.StyledPanel)
        self.frame_6.setFrameShadow(QFrame.Shadow.Raised)
        self.groupBox_2 = QGroupBox(self.frame_6)
        self.groupBox_2.setObjectName(u"groupBox_2")
        self.groupBox_2.setGeometry(QRect(0, 10, 191, 80))
        self.radioButton_bounded = QRadioButton(self.groupBox_2)
        self.radioButton_bounded.setObjectName(u"radioButton_bounded")
        self.radioButton_bounded.setGeometry(QRect(0, 20, 89, 20))
        self.radioButton_bounded.setChecked(True)
        self.radioButton_lower = QRadioButton(self.groupBox_2)
        self.radioButton_lower.setObjectName(u"radioButton_lower")
        self.radioButton_lower.setGeometry(QRect(0, 40, 89, 20))
        self.radioButton_upper = QRadioButton(self.groupBox_2)
        self.radioButton_upper.setObjectName(u"radioButton_upper")
        self.radioButton_upper.setGeometry(QRect(0, 60, 89, 20))
        self.groupBox_12 = QGroupBox(self.frame_6)
        self.groupBox_12.setObjectName(u"groupBox_12")
        self.groupBox_12.setGeometry(QRect(0, 110, 191, 51))
        self.doubleSpinBox_lower = QDoubleSpinBox(self.groupBox_12)
        self.doubleSpinBox_lower.setObjectName(u"doubleSpinBox_lower")
        self.doubleSpinBox_lower.setGeometry(QRect(140, 10, 51, 30))
        self.doubleSpinBox_lower.setMaximumSize(QSize(16777215, 30))
        self.doubleSpinBox_lower.setMaximum(105.000000000000000)
        self.doubleSpinBox_lower.setSingleStep(0.100000000000000)
        self.ScrollBar_lower = QSlider(self.groupBox_12)
        self.ScrollBar_lower.setObjectName(u"ScrollBar_lower")
        self.ScrollBar_lower.setGeometry(QRect(10, 20, 121, 22))
        self.ScrollBar_lower.setMaximum(105)
        self.ScrollBar_lower.setSingleStep(1)
        self.ScrollBar_lower.setPageStep(10)
        self.ScrollBar_lower.setValue(0)
        self.ScrollBar_lower.setOrientation(Qt.Orientation.Horizontal)
        self.groupBox_21 = QGroupBox(self.frame_6)
        self.groupBox_21.setObjectName(u"groupBox_21")
        self.groupBox_21.setGeometry(QRect(0, 180, 191, 51))
        self.doubleSpinBox_upper = QDoubleSpinBox(self.groupBox_21)
        self.doubleSpinBox_upper.setObjectName(u"doubleSpinBox_upper")
        self.doubleSpinBox_upper.setGeometry(QRect(140, 10, 51, 30))
        self.doubleSpinBox_upper.setMaximumSize(QSize(16777215, 30))
        self.doubleSpinBox_upper.setMaximum(105.000000000000000)
        self.doubleSpinBox_upper.setSingleStep(0.100000000000000)
        self.ScrollBar_upper = QSlider(self.groupBox_21)
        self.ScrollBar_upper.setObjectName(u"ScrollBar_upper")
        self.ScrollBar_upper.setGeometry(QRect(10, 20, 121, 22))
        self.ScrollBar_upper.setMaximum(105)
        self.ScrollBar_upper.setSingleStep(1)
        self.ScrollBar_upper.setPageStep(10)
        self.ScrollBar_upper.setValue(0)
        self.ScrollBar_upper.setOrientation(Qt.Orientation.Horizontal)
        self.pushButton_3 = QPushButton(self.page)
        self.pushButton_3.setObjectName(u"pushButton_3")
        self.pushButton_3.setEnabled(False)
        self.pushButton_3.setGeometry(QRect(30, 360, 75, 24))
        self.pushButton_Next1 = QPushButton(self.page)
        self.pushButton_Next1.setObjectName(u"pushButton_Next1")
        self.pushButton_Next1.setGeometry(QRect(110, 360, 75, 24))
        self.textBrowser = QTextBrowser(self.page)
        self.textBrowser.setObjectName(u"textBrowser")
        self.textBrowser.setGeometry(QRect(30, 0, 161, 51))
        self.textBrowser.setStyleSheet(u"")
        self.textBrowser.setVerticalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.textBrowser.setHorizontalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.stackedWidget.addWidget(self.page)
        self.initialization = QWidget()
        self.initialization.setObjectName(u"initialization")
        self.pushButton_addBubbles = QPushButton(self.initialization)
        self.pushButton_addBubbles.setObjectName(u"pushButton_addBubbles")
        self.pushButton_addBubbles.setGeometry(QRect(40, 70, 131, 24))
        self.groupBox_4 = QGroupBox(self.initialization)
        self.groupBox_4.setObjectName(u"groupBox_4")
        self.groupBox_4.setGeometry(QRect(20, 100, 181, 51))
        self.doubleSpinBox_Bubradius = QDoubleSpinBox(self.groupBox_4)
        self.doubleSpinBox_Bubradius.setObjectName(u"doubleSpinBox_Bubradius")
        self.doubleSpinBox_Bubradius.setGeometry(QRect(10, 20, 31, 20))
        self.doubleSpinBox_Bubradius.setMaximumSize(QSize(16777215, 30))
        self.doubleSpinBox_Bubradius.setFrame(True)
        self.doubleSpinBox_Bubradius.setButtonSymbols(QAbstractSpinBox.ButtonSymbols.NoButtons)
        self.doubleSpinBox_Bubradius.setMaximum(105.000000000000000)
        self.doubleSpinBox_Bubradius.setSingleStep(0.100000000000000)
        self.horizontalSlider_Bubradius = QSlider(self.groupBox_4)
        self.horizontalSlider_Bubradius.setObjectName(u"horizontalSlider_Bubradius")
        self.horizontalSlider_Bubradius.setGeometry(QRect(50, 20, 121, 22))
        self.horizontalSlider_Bubradius.setMaximum(600)
        self.horizontalSlider_Bubradius.setSingleStep(1)
        self.horizontalSlider_Bubradius.setPageStep(1)
        self.horizontalSlider_Bubradius.setValue(0)
        self.horizontalSlider_Bubradius.setOrientation(Qt.Orientation.Horizontal)
        self.pushButton_delete = QPushButton(self.initialization)
        self.pushButton_delete.setObjectName(u"pushButton_delete")
        self.pushButton_delete.setGeometry(QRect(40, 320, 131, 24))
        self.groupBox_5 = QGroupBox(self.initialization)
        self.groupBox_5.setObjectName(u"groupBox_5")
        self.groupBox_5.setGeometry(QRect(20, 160, 181, 151))
        self.tableView_activeBub = QTableView(self.groupBox_5)
        self.tableView_activeBub.setObjectName(u"tableView_activeBub")
        self.tableView_activeBub.setEnabled(True)
        self.tableView_activeBub.setGeometry(QRect(0, 20, 181, 131))
        self.tableView_activeBub.setHorizontalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.tableView_activeBub.setEditTriggers(QAbstractItemView.EditTrigger.NoEditTriggers)
        self.tableView_activeBub.setSelectionMode(QAbstractItemView.SelectionMode.SingleSelection)
        self.tableView_activeBub.setSelectionBehavior(QAbstractItemView.SelectionBehavior.SelectRows)
        self.tableView_activeBub.horizontalHeader().setCascadingSectionResizes(False)
        self.textBrowser_2 = QTextBrowser(self.initialization)
        self.textBrowser_2.setObjectName(u"textBrowser_2")
        self.textBrowser_2.setGeometry(QRect(30, 0, 161, 51))
        self.textBrowser_2.setStyleSheet(u"")
        self.textBrowser_2.setVerticalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.textBrowser_2.setHorizontalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.pushButton_Back2 = QPushButton(self.initialization)
        self.pushButton_Back2.setObjectName(u"pushButton_Back2")
        self.pushButton_Back2.setEnabled(True)
        self.pushButton_Back2.setGeometry(QRect(30, 360, 75, 24))
        self.pushButton_Next2 = QPushButton(self.initialization)
        self.pushButton_Next2.setObjectName(u"pushButton_Next2")
        self.pushButton_Next2.setEnabled(False)
        self.pushButton_Next2.setGeometry(QRect(110, 360, 75, 24))
        self.stackedWidget.addWidget(self.initialization)
        self.page_3 = QWidget()
        self.page_3.setObjectName(u"page_3")
        self.textBrowser_3 = QTextBrowser(self.page_3)
        self.textBrowser_3.setObjectName(u"textBrowser_3")
        self.textBrowser_3.setGeometry(QRect(30, 0, 161, 51))
        self.textBrowser_3.setStyleSheet(u"")
        self.textBrowser_3.setVerticalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.textBrowser_3.setHorizontalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.pushButton_Back3 = QPushButton(self.page_3)
        self.pushButton_Back3.setObjectName(u"pushButton_Back3")
        self.pushButton_Back3.setEnabled(True)
        self.pushButton_Back3.setGeometry(QRect(30, 360, 75, 24))
        self.pushButton_Finish = QPushButton(self.page_3)
        self.pushButton_Finish.setObjectName(u"pushButton_Finish")
        self.pushButton_Finish.setEnabled(True)
        self.pushButton_Finish.setGeometry(QRect(110, 360, 75, 24))
        self.toolButton_runEvo = QToolButton(self.page_3)
        self.toolButton_runEvo.setObjectName(u"toolButton_runEvo")
        self.toolButton_runEvo.setGeometry(QRect(90, 150, 31, 31))
        icon3 = QIcon(QIcon.fromTheme(QIcon.ThemeIcon.MediaPlaybackStart))
        self.toolButton_runEvo.setIcon(icon3)
        self.toolButton_runEvo.setIconSize(QSize(20, 20))
        self.toolButton_runEvo.setCheckable(True)
        self.toolButton_2 = QToolButton(self.page_3)
        self.toolButton_2.setObjectName(u"toolButton_2")
        self.toolButton_2.setGeometry(QRect(50, 150, 31, 31))
        icon4 = QIcon(QIcon.fromTheme(QIcon.ThemeIcon.MediaSeekBackward))
        self.toolButton_2.setIcon(icon4)
        self.toolButton_2.setIconSize(QSize(20, 20))
        self.toolButton_3 = QToolButton(self.page_3)
        self.toolButton_3.setObjectName(u"toolButton_3")
        self.toolButton_3.setGeometry(QRect(130, 150, 31, 31))
        icon5 = QIcon(QIcon.fromTheme(QIcon.ThemeIcon.MediaSeekForward))
        self.toolButton_3.setIcon(icon5)
        self.toolButton_3.setIconSize(QSize(20, 20))
        self.groupBox_9 = QGroupBox(self.page_3)
        self.groupBox_9.setObjectName(u"groupBox_9")
        self.groupBox_9.setGeometry(QRect(40, 230, 61, 61))
        self.doubleSpinBox_Bubradius_2 = QDoubleSpinBox(self.groupBox_9)
        self.doubleSpinBox_Bubradius_2.setObjectName(u"doubleSpinBox_Bubradius_2")
        self.doubleSpinBox_Bubradius_2.setGeometry(QRect(10, 20, 41, 30))
        self.doubleSpinBox_Bubradius_2.setMaximumSize(QSize(16777215, 30))
        self.doubleSpinBox_Bubradius_2.setFrame(True)
        self.doubleSpinBox_Bubradius_2.setButtonSymbols(QAbstractSpinBox.ButtonSymbols.NoButtons)
        self.doubleSpinBox_Bubradius_2.setMaximum(105.000000000000000)
        self.doubleSpinBox_Bubradius_2.setSingleStep(0.100000000000000)
        self.groupBox_11 = QGroupBox(self.page_3)
        self.groupBox_11.setObjectName(u"groupBox_11")
        self.groupBox_11.setGeometry(QRect(120, 230, 61, 61))
        self.doubleSpinBox_Bubradius_4 = QDoubleSpinBox(self.groupBox_11)
        self.doubleSpinBox_Bubradius_4.setObjectName(u"doubleSpinBox_Bubradius_4")
        self.doubleSpinBox_Bubradius_4.setGeometry(QRect(10, 20, 41, 30))
        self.doubleSpinBox_Bubradius_4.setMaximumSize(QSize(16777215, 30))
        self.doubleSpinBox_Bubradius_4.setFrame(True)
        self.doubleSpinBox_Bubradius_4.setButtonSymbols(QAbstractSpinBox.ButtonSymbols.NoButtons)
        self.doubleSpinBox_Bubradius_4.setMaximum(105.000000000000000)
        self.doubleSpinBox_Bubradius_4.setSingleStep(0.100000000000000)
        self.stackedWidget.addWidget(self.page_3)
        icon6 = QIcon()
        icon6.addFile(u"Icons/ITKsnap/snake.gif", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.toolbar.addTab(self.tab, icon6, "")
        self.tab_4 = QWidget()
        self.tab_4.setObjectName(u"tab_4")
        self.groupBox_13 = QGroupBox(self.tab_4)
        self.groupBox_13.setObjectName(u"groupBox_13")
        self.groupBox_13.setGeometry(QRect(10, 10, 191, 221))
        self.groupBox_14 = QGroupBox(self.groupBox_13)
        self.groupBox_14.setObjectName(u"groupBox_14")
        self.groupBox_14.setGeometry(QRect(10, 20, 171, 51))
        self.paint_square = QToolButton(self.groupBox_14)
        self.paint_square.setObjectName(u"paint_square")
        self.paint_square.setGeometry(QRect(20, 21, 31, 21))
        icon7 = QIcon()
        icon7.addFile(u"Icons/ITKsnap/brush_shape_square.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.paint_square.setIcon(icon7)
        self.paint_square.setIconSize(QSize(20, 20))
        self.paint_square.setAutoExclusive(False)
        self.paint_round = QToolButton(self.groupBox_14)
        self.paint_round.setObjectName(u"paint_round")
        self.paint_round.setEnabled(True)
        self.paint_round.setGeometry(QRect(70, 20, 31, 22))
        icon8 = QIcon()
        icon8.addFile(u"Icons/ITKsnap/brush_shape_round.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.paint_round.setIcon(icon8)
        self.paint_round.setIconSize(QSize(20, 20))
        self.paint_round.setCheckable(False)
        self.paint_round.setAutoExclusive(False)
        self.paint_adjusted = QToolButton(self.groupBox_14)
        self.paint_adjusted.setObjectName(u"paint_adjusted")
        self.paint_adjusted.setEnabled(False)
        self.paint_adjusted.setGeometry(QRect(120, 20, 31, 22))
        icon9 = QIcon()
        icon9.addFile(u"Icons/ITKsnap/brush_shape_adaptive.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.paint_adjusted.setIcon(icon9)
        self.paint_adjusted.setIconSize(QSize(20, 20))
        self.groupBox_15 = QGroupBox(self.groupBox_13)
        self.groupBox_15.setObjectName(u"groupBox_15")
        self.groupBox_15.setGeometry(QRect(10, 80, 171, 51))
        self.brush_size = QDoubleSpinBox(self.groupBox_15)
        self.brush_size.setObjectName(u"brush_size")
        self.brush_size.setGeometry(QRect(10, 20, 41, 20))
        self.brush_size.setMaximumSize(QSize(16777215, 30))
        self.brush_size.setWrapping(False)
        self.brush_size.setFrame(True)
        self.brush_size.setButtonSymbols(QAbstractSpinBox.ButtonSymbols.UpDownArrows)
        self.brush_size.setDecimals(0)
        self.brush_size.setMaximum(40.000000000000000)
        self.brush_size.setSingleStep(1.000000000000000)
        self.brush_sizeSlider = QSlider(self.groupBox_15)
        self.brush_sizeSlider.setObjectName(u"brush_sizeSlider")
        self.brush_sizeSlider.setGeometry(QRect(60, 20, 101, 22))
        self.brush_sizeSlider.setMaximum(600)
        self.brush_sizeSlider.setSingleStep(1)
        self.brush_sizeSlider.setPageStep(1)
        self.brush_sizeSlider.setValue(0)
        self.brush_sizeSlider.setOrientation(Qt.Orientation.Horizontal)
        self.groupBox_17 = QGroupBox(self.groupBox_13)
        self.groupBox_17.setObjectName(u"groupBox_17")
        self.groupBox_17.setGeometry(QRect(10, 140, 171, 71))
        self.brush_3d = QCheckBox(self.groupBox_17)
        self.brush_3d.setObjectName(u"brush_3d")
        self.brush_3d.setGeometry(QRect(10, 20, 41, 20))
        self.checkBox_2 = QCheckBox(self.groupBox_17)
        self.checkBox_2.setObjectName(u"checkBox_2")
        self.checkBox_2.setEnabled(False)
        self.checkBox_2.setGeometry(QRect(90, 20, 71, 20))
        self.checkBox_3 = QCheckBox(self.groupBox_17)
        self.checkBox_3.setObjectName(u"checkBox_3")
        self.checkBox_3.setEnabled(False)
        self.checkBox_3.setGeometry(QRect(10, 40, 131, 20))
        self.groupBox_18 = QGroupBox(self.tab_4)
        self.groupBox_18.setObjectName(u"groupBox_18")
        self.groupBox_18.setGeometry(QRect(10, 240, 191, 181))
        self.groupBox_16 = QGroupBox(self.groupBox_18)
        self.groupBox_16.setObjectName(u"groupBox_16")
        self.groupBox_16.setGeometry(QRect(10, 20, 171, 51))
        self.comboBox_activeLabels = QComboBox(self.groupBox_16)
        self.comboBox_activeLabels.setObjectName(u"comboBox_activeLabels")
        self.comboBox_activeLabels.setEnabled(True)
        self.comboBox_activeLabels.setGeometry(QRect(10, 20, 151, 22))
        self.groupBox_19 = QGroupBox(self.groupBox_18)
        self.groupBox_19.setObjectName(u"groupBox_19")
        self.groupBox_19.setGeometry(QRect(10, 70, 171, 51))
        self.comboBox_paintOver = QComboBox(self.groupBox_19)
        self.comboBox_paintOver.setObjectName(u"comboBox_paintOver")
        self.comboBox_paintOver.setGeometry(QRect(10, 20, 151, 22))
        self.groupBox_20 = QGroupBox(self.groupBox_18)
        self.groupBox_20.setObjectName(u"groupBox_20")
        self.groupBox_20.setGeometry(QRect(10, 120, 171, 51))
        self.doubleSpinBox_Bubradius_5 = QDoubleSpinBox(self.groupBox_20)
        self.doubleSpinBox_Bubradius_5.setObjectName(u"doubleSpinBox_Bubradius_5")
        self.doubleSpinBox_Bubradius_5.setGeometry(QRect(10, 20, 31, 20))
        self.doubleSpinBox_Bubradius_5.setMaximumSize(QSize(16777215, 30))
        self.doubleSpinBox_Bubradius_5.setFrame(True)
        self.doubleSpinBox_Bubradius_5.setButtonSymbols(QAbstractSpinBox.ButtonSymbols.NoButtons)
        self.doubleSpinBox_Bubradius_5.setMaximum(105.000000000000000)
        self.doubleSpinBox_Bubradius_5.setSingleStep(0.100000000000000)
        self.horizontalSlider_Bubradius_3 = QSlider(self.groupBox_20)
        self.horizontalSlider_Bubradius_3.setObjectName(u"horizontalSlider_Bubradius_3")
        self.horizontalSlider_Bubradius_3.setGeometry(QRect(50, 20, 111, 22))
        self.horizontalSlider_Bubradius_3.setMaximum(600)
        self.horizontalSlider_Bubradius_3.setSingleStep(1)
        self.horizontalSlider_Bubradius_3.setPageStep(1)
        self.horizontalSlider_Bubradius_3.setValue(0)
        self.horizontalSlider_Bubradius_3.setOrientation(Qt.Orientation.Horizontal)
        icon10 = QIcon()
        icon10.addFile(u"Icons/ITKsnap/paintbrush.gif", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.toolbar.addTab(self.tab_4, icon10, "")
        self.tab_5 = QWidget()
        self.tab_5.setObjectName(u"tab_5")
        self.groupBox = QGroupBox(self.tab_5)
        self.groupBox.setObjectName(u"groupBox")
        self.groupBox.setGeometry(QRect(10, 20, 191, 51))
        self.pushButton_2 = QPushButton(self.groupBox)
        self.pushButton_2.setObjectName(u"pushButton_2")
        self.pushButton_2.setGeometry(QRect(20, 20, 131, 24))
        icon11 = QIcon()
        icon11.addFile(u"Icons/Internet/platz.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.pushButton_2.setIcon(icon11)
        self.groupBox_3 = QGroupBox(self.tab_5)
        self.groupBox_3.setObjectName(u"groupBox_3")
        self.groupBox_3.setGeometry(QRect(10, 80, 191, 51))
        self.pushButton_4 = QPushButton(self.groupBox_3)
        self.pushButton_4.setObjectName(u"pushButton_4")
        self.pushButton_4.setGeometry(QRect(20, 20, 131, 24))
        self.pushButton_4.setIcon(icon11)
        self.groupBox_22 = QGroupBox(self.tab_5)
        self.groupBox_22.setObjectName(u"groupBox_22")
        self.groupBox_22.setGeometry(QRect(10, 150, 191, 51))
        self.spinBox_y_2 = QSpinBox(self.groupBox_22)
        self.spinBox_y_2.setObjectName(u"spinBox_y_2")
        self.spinBox_y_2.setGeometry(QRect(70, 20, 42, 22))
        self.spinBox_y_2.setButtonSymbols(QAbstractSpinBox.ButtonSymbols.NoButtons)
        self.spinBox_y_2.setMinimum(1)
        self.spinBox_y_2.setMaximum(120)
        self.toolbar.addTab(self.tab_5, icon11, "")
        self.frame = QFrame(self.PreSurgery)
        self.frame.setObjectName(u"frame")
        self.frame.setGeometry(QRect(250, 320, 441, 271))
        self.frame.setStyleSheet(u"border-color: rgb(170, 170, 170);\n"
"background-color: rgb(131, 131, 131);")
        self.frame.setFrameShape(QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QFrame.Shadow.Raised)
        self.frame.setLineWidth(2)
        self.frame_2 = QFrame(self.PreSurgery)
        self.frame_2.setObjectName(u"frame_2")
        self.frame_2.setGeometry(QRect(700, 320, 441, 271))
        self.frame_2.setStyleSheet(u"border-color: rgb(170, 170, 170);\n"
"background-color: rgb(131, 131, 131);\n"
"")
        self.frame_2.setFrameShape(QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QFrame.Shadow.Raised)
        self.fit_to_zoom_axial = QPushButton(self.frame_2)
        self.fit_to_zoom_axial.setObjectName(u"fit_to_zoom_axial")
        self.fit_to_zoom_axial.setGeometry(QRect(0, 250, 81, 21))
        self.fit_to_zoom_axial.setStyleSheet(u"\n"
"background-color: rgb(0, 153, 255);")
        self.fit_to_zoom_axial.setAutoDefault(False)
        self.fit_to_zoom_axial.setFlat(False)
        self.zoom_in_axial = QToolButton(self.frame_2)
        self.zoom_in_axial.setObjectName(u"zoom_in_axial")
        self.zoom_in_axial.setGeometry(QRect(80, 250, 22, 22))
        self.zoom_out_axial = QToolButton(self.frame_2)
        self.zoom_out_axial.setObjectName(u"zoom_out_axial")
        self.zoom_out_axial.setGeometry(QRect(100, 250, 22, 22))
        self.vtkWidget_axial = QVTKRenderWindowInteractor(self.frame_2)
        self.vtkWidget_axial.setObjectName(u"vtkWidget_axial")
        self.vtkWidget_axial.setGeometry(QRect(10, 10, 421, 241))
        self.vtkWidget_axial.setStyleSheet(u"background-color: rgb(200, 177, 176);")
        self.Scroll_axial = QScrollBar(self.frame_2)
        self.Scroll_axial.setObjectName(u"Scroll_axial")
        self.Scroll_axial.setGeometry(QRect(420, 10, 16, 241))
        self.Scroll_axial.setOrientation(Qt.Orientation.Vertical)
        self.frame_4 = QFrame(self.PreSurgery)
        self.frame_4.setObjectName(u"frame_4")
        self.frame_4.setGeometry(QRect(700, 40, 441, 271))
        self.frame_4.setStyleSheet(u"border-color: rgb(170, 170, 170);\n"
"background-color: rgb(131, 131, 131);\n"
"\n"
"")
        self.frame_4.setFrameShape(QFrame.Shape.StyledPanel)
        self.frame_4.setFrameShadow(QFrame.Shadow.Raised)
        self.fit_to_zoom_sagittal = QPushButton(self.frame_4)
        self.fit_to_zoom_sagittal.setObjectName(u"fit_to_zoom_sagittal")
        self.fit_to_zoom_sagittal.setGeometry(QRect(10, 250, 81, 21))
        self.fit_to_zoom_sagittal.setStyleSheet(u"\n"
"background-color: rgb(0, 153, 255);")
        self.fit_to_zoom_sagittal.setAutoDefault(False)
        self.fit_to_zoom_sagittal.setFlat(False)
        self.zoom_out_sagittal = QToolButton(self.frame_4)
        self.zoom_out_sagittal.setObjectName(u"zoom_out_sagittal")
        self.zoom_out_sagittal.setGeometry(QRect(110, 250, 22, 22))
        self.zoom_in_sagittal = QToolButton(self.frame_4)
        self.zoom_in_sagittal.setObjectName(u"zoom_in_sagittal")
        self.zoom_in_sagittal.setGeometry(QRect(90, 250, 22, 22))
        self.vtkWidget_sagittal = QVTKRenderWindowInteractor(self.frame_4)
        self.vtkWidget_sagittal.setObjectName(u"vtkWidget_sagittal")
        self.vtkWidget_sagittal.setGeometry(QRect(10, 10, 421, 241))
        self.vtkWidget_sagittal.setStyleSheet(u"background-color: rgb(200, 177, 176);")
        self.Scroll_sagittal = QScrollBar(self.frame_4)
        self.Scroll_sagittal.setObjectName(u"Scroll_sagittal")
        self.Scroll_sagittal.setGeometry(QRect(420, 10, 16, 241))
        self.Scroll_sagittal.setOrientation(Qt.Orientation.Vertical)
        self.frame_5 = QFrame(self.PreSurgery)
        self.frame_5.setObjectName(u"frame_5")
        self.frame_5.setGeometry(QRect(250, 40, 441, 271))
        self.frame_5.setStyleSheet(u"border-color: rgb(170, 170, 170);\n"
"background-color: rgb(131, 131, 131);")
        self.frame_5.setFrameShape(QFrame.Shape.StyledPanel)
        self.frame_5.setFrameShadow(QFrame.Shadow.Raised)
        self.vtkWidget_coronal = QVTKRenderWindowInteractor(self.frame_5)
        self.vtkWidget_coronal.setObjectName(u"vtkWidget_coronal")
        self.vtkWidget_coronal.setGeometry(QRect(10, 10, 421, 241))
        self.vtkWidget_coronal.setStyleSheet(u"background-color: rgb(200, 177, 176);")
        self.fit_to_zoom_coronal = QPushButton(self.frame_5)
        self.fit_to_zoom_coronal.setObjectName(u"fit_to_zoom_coronal")
        self.fit_to_zoom_coronal.setGeometry(QRect(10, 250, 81, 21))
        self.fit_to_zoom_coronal.setStyleSheet(u"\n"
"background-color: rgb(0, 153, 255);")
        self.fit_to_zoom_coronal.setAutoDefault(False)
        self.fit_to_zoom_coronal.setFlat(False)
        self.zoom_in_coronal = QToolButton(self.frame_5)
        self.zoom_in_coronal.setObjectName(u"zoom_in_coronal")
        self.zoom_in_coronal.setGeometry(QRect(90, 250, 22, 22))
        self.zoom_out_coronal = QToolButton(self.frame_5)
        self.zoom_out_coronal.setObjectName(u"zoom_out_coronal")
        self.zoom_out_coronal.setGeometry(QRect(110, 250, 22, 22))
        self.Scroll_coronal = QScrollBar(self.frame_5)
        self.Scroll_coronal.setObjectName(u"Scroll_coronal")
        self.Scroll_coronal.setGeometry(QRect(420, 10, 16, 241))
        self.Scroll_coronal.setOrientation(Qt.Orientation.Vertical)
        self.file_name_displayed = QTextEdit(self.PreSurgery)
        self.file_name_displayed.setObjectName(u"file_name_displayed")
        self.file_name_displayed.setGeometry(QRect(10, 10, 1131, 25))
        font1 = QFont()
        font1.setBold(True)
        self.file_name_displayed.setFont(font1)
        self.groupBox_6 = QGroupBox(self.PreSurgery)
        self.groupBox_6.setObjectName(u"groupBox_6")
        self.groupBox_6.setGeometry(QRect(30, 500, 161, 51))
        self.spinBox_x = QSpinBox(self.groupBox_6)
        self.spinBox_x.setObjectName(u"spinBox_x")
        self.spinBox_x.setGeometry(QRect(10, 20, 42, 22))
        self.spinBox_x.setButtonSymbols(QAbstractSpinBox.ButtonSymbols.NoButtons)
        self.spinBox_x.setMinimum(1)
        self.spinBox_x.setMaximum(180)
        self.spinBox_y = QSpinBox(self.groupBox_6)
        self.spinBox_y.setObjectName(u"spinBox_y")
        self.spinBox_y.setGeometry(QRect(60, 20, 42, 22))
        self.spinBox_y.setButtonSymbols(QAbstractSpinBox.ButtonSymbols.NoButtons)
        self.spinBox_y.setMinimum(1)
        self.spinBox_y.setMaximum(120)
        self.spinBox_z = QSpinBox(self.groupBox_6)
        self.spinBox_z.setObjectName(u"spinBox_z")
        self.spinBox_z.setGeometry(QRect(110, 20, 42, 22))
        self.spinBox_z.setButtonSymbols(QAbstractSpinBox.ButtonSymbols.NoButtons)
        self.spinBox_z.setMinimum(1)
        self.spinBox_z.setMaximum(60)
        self.groupBox_7 = QGroupBox(self.PreSurgery)
        self.groupBox_7.setObjectName(u"groupBox_7")
        self.groupBox_7.setGeometry(QRect(10, 560, 211, 91))
        self.label_4 = QLabel(self.groupBox_7)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(60, 30, 81, 21))
        self.label_4.setFont(font)
        self.label_5 = QLabel(self.groupBox_7)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(10, 60, 131, 21))
        self.label_5.setFont(font)
        self.x_7 = QLCDNumber(self.groupBox_7)
        self.x_7.setObjectName(u"x_7")
        self.x_7.setGeometry(QRect(140, 30, 61, 21))
        self.x_7.setMaximumSize(QSize(16777215, 100))
        self.x_7.setAutoFillBackground(False)
        self.x_7.setStyleSheet(u"color: rgb(0, 0, 0); background-color: white;")
        self.x_8 = QLCDNumber(self.groupBox_7)
        self.x_8.setObjectName(u"x_8")
        self.x_8.setGeometry(QRect(140, 60, 61, 21))
        self.x_8.setMaximumSize(QSize(16777215, 100))
        self.x_8.setStyleSheet(u"color: rgb(0, 0, 0); background-color: white;")
        self.checkBox_measurement = QCheckBox(self.PreSurgery)
        self.checkBox_measurement.setObjectName(u"checkBox_measurement")
        self.checkBox_measurement.setEnabled(True)
        self.checkBox_measurement.setGeometry(QRect(260, 610, 121, 41))
        icon12 = QIcon()
        icon12.addFile(u"Icons/Internet/measure.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.checkBox_measurement.setIcon(icon12)
        self.checkBox_measurement.setIconSize(QSize(30, 30))
        self.checkBox_measurement.setChecked(False)
        self.tabWidget.addTab(self.PreSurgery, "")
        self.frame_2.raise_()
        self.frame.raise_()
        self.frame_4.raise_()
        self.frame_5.raise_()
        self.graphicsView_2.raise_()
        self.toolbar.raise_()
        self.file_name_displayed.raise_()
        self.groupBox_6.raise_()
        self.groupBox_7.raise_()
        self.checkBox_measurement.raise_()
        self.PostSurgery = QWidget()
        self.PostSurgery.setObjectName(u"PostSurgery")
        self.toolButton_LoadFile_Post = QToolButton(self.PostSurgery)
        self.toolButton_LoadFile_Post.setObjectName(u"toolButton_LoadFile_Post")
        self.toolButton_LoadFile_Post.setGeometry(QRect(20, 570, 61, 61))
        self.toolButton_LoadFile_Post.setToolTipDuration(0)
        self.toolButton_LoadFile_Post.setIcon(icon)
        self.toolButton_LoadFile_Post.setIconSize(QSize(30, 30))
        self.groupBox_23 = QGroupBox(self.PostSurgery)
        self.groupBox_23.setObjectName(u"groupBox_23")
        self.groupBox_23.setEnabled(False)
        self.groupBox_23.setGeometry(QRect(100, 580, 121, 51))
        self.comboBox_3 = QComboBox(self.groupBox_23)
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.setObjectName(u"comboBox_3")
        self.comboBox_3.setEnabled(False)
        self.comboBox_3.setGeometry(QRect(10, 20, 101, 22))
        self.file_name_displayed_Post = QTextEdit(self.PostSurgery)
        self.file_name_displayed_Post.setObjectName(u"file_name_displayed_Post")
        self.file_name_displayed_Post.setGeometry(QRect(20, 0, 771, 25))
        self.file_name_displayed_Post.setFont(font1)
        self.groupBox_24 = QGroupBox(self.PostSurgery)
        self.groupBox_24.setObjectName(u"groupBox_24")
        self.groupBox_24.setGeometry(QRect(20, 640, 161, 51))
        self.spinBox_x_Post = QSpinBox(self.groupBox_24)
        self.spinBox_x_Post.setObjectName(u"spinBox_x_Post")
        self.spinBox_x_Post.setGeometry(QRect(10, 20, 42, 22))
        self.spinBox_x_Post.setButtonSymbols(QAbstractSpinBox.ButtonSymbols.NoButtons)
        self.spinBox_x_Post.setMinimum(1)
        self.spinBox_x_Post.setMaximum(180)
        self.spinBox_y_Post = QSpinBox(self.groupBox_24)
        self.spinBox_y_Post.setObjectName(u"spinBox_y_Post")
        self.spinBox_y_Post.setGeometry(QRect(60, 20, 42, 22))
        self.spinBox_y_Post.setButtonSymbols(QAbstractSpinBox.ButtonSymbols.NoButtons)
        self.spinBox_y_Post.setMinimum(1)
        self.spinBox_y_Post.setMaximum(120)
        self.spinBox_z_Post = QSpinBox(self.groupBox_24)
        self.spinBox_z_Post.setObjectName(u"spinBox_z_Post")
        self.spinBox_z_Post.setGeometry(QRect(110, 20, 42, 22))
        self.spinBox_z_Post.setButtonSymbols(QAbstractSpinBox.ButtonSymbols.NoButtons)
        self.spinBox_z_Post.setMinimum(1)
        self.spinBox_z_Post.setMaximum(60)
        self.groupBox_25 = QGroupBox(self.PostSurgery)
        self.groupBox_25.setObjectName(u"groupBox_25")
        self.groupBox_25.setGeometry(QRect(20, 700, 131, 51))
        self.x_7_Post = QLCDNumber(self.groupBox_25)
        self.x_7_Post.setObjectName(u"x_7_Post")
        self.x_7_Post.setGeometry(QRect(60, 20, 61, 21))
        self.x_7_Post.setMaximumSize(QSize(16777215, 100))
        self.x_7_Post.setAutoFillBackground(False)
        self.x_7_Post.setStyleSheet(u"color: rgb(0, 0, 0); background-color: white;")
        self.groupBox_32 = QGroupBox(self.PostSurgery)
        self.groupBox_32.setObjectName(u"groupBox_32")
        self.groupBox_32.setGeometry(QRect(1150, 40, 211, 421))
        self.groupBox_28 = QGroupBox(self.groupBox_32)
        self.groupBox_28.setObjectName(u"groupBox_28")
        self.groupBox_28.setGeometry(QRect(10, 50, 191, 221))
        self.groupBox_29 = QGroupBox(self.groupBox_28)
        self.groupBox_29.setObjectName(u"groupBox_29")
        self.groupBox_29.setGeometry(QRect(10, 20, 171, 51))
        self.paint_square_Post = QToolButton(self.groupBox_29)
        self.paint_square_Post.setObjectName(u"paint_square_Post")
        self.paint_square_Post.setGeometry(QRect(20, 21, 31, 21))
        self.paint_square_Post.setIcon(icon7)
        self.paint_square_Post.setIconSize(QSize(20, 20))
        self.paint_square_Post.setAutoExclusive(False)
        self.paint_round_Post = QToolButton(self.groupBox_29)
        self.paint_round_Post.setObjectName(u"paint_round_Post")
        self.paint_round_Post.setEnabled(True)
        self.paint_round_Post.setGeometry(QRect(70, 20, 31, 22))
        self.paint_round_Post.setIcon(icon8)
        self.paint_round_Post.setIconSize(QSize(20, 20))
        self.paint_round_Post.setCheckable(False)
        self.paint_round_Post.setAutoExclusive(False)
        self.paint_adjusted_2 = QToolButton(self.groupBox_29)
        self.paint_adjusted_2.setObjectName(u"paint_adjusted_2")
        self.paint_adjusted_2.setEnabled(False)
        self.paint_adjusted_2.setGeometry(QRect(120, 20, 31, 22))
        self.paint_adjusted_2.setIcon(icon9)
        self.paint_adjusted_2.setIconSize(QSize(20, 20))
        self.groupBox_30 = QGroupBox(self.groupBox_28)
        self.groupBox_30.setObjectName(u"groupBox_30")
        self.groupBox_30.setGeometry(QRect(10, 80, 171, 51))
        self.brush_size_Post = QDoubleSpinBox(self.groupBox_30)
        self.brush_size_Post.setObjectName(u"brush_size_Post")
        self.brush_size_Post.setGeometry(QRect(10, 20, 41, 20))
        self.brush_size_Post.setMaximumSize(QSize(16777215, 30))
        self.brush_size_Post.setWrapping(False)
        self.brush_size_Post.setFrame(True)
        self.brush_size_Post.setButtonSymbols(QAbstractSpinBox.ButtonSymbols.UpDownArrows)
        self.brush_size_Post.setDecimals(0)
        self.brush_size_Post.setMinimum(1.000000000000000)
        self.brush_size_Post.setMaximum(40.000000000000000)
        self.brush_size_Post.setSingleStep(1.000000000000000)
        self.brush_sizeSlider_Post = QSlider(self.groupBox_30)
        self.brush_sizeSlider_Post.setObjectName(u"brush_sizeSlider_Post")
        self.brush_sizeSlider_Post.setGeometry(QRect(60, 20, 101, 22))
        self.brush_sizeSlider_Post.setMinimum(1)
        self.brush_sizeSlider_Post.setMaximum(40)
        self.brush_sizeSlider_Post.setSingleStep(1)
        self.brush_sizeSlider_Post.setPageStep(1)
        self.brush_sizeSlider_Post.setValue(1)
        self.brush_sizeSlider_Post.setOrientation(Qt.Orientation.Horizontal)
        self.groupBox_31 = QGroupBox(self.groupBox_28)
        self.groupBox_31.setObjectName(u"groupBox_31")
        self.groupBox_31.setGeometry(QRect(10, 140, 171, 71))
        self.brush_3d_2 = QCheckBox(self.groupBox_31)
        self.brush_3d_2.setObjectName(u"brush_3d_2")
        self.brush_3d_2.setEnabled(False)
        self.brush_3d_2.setGeometry(QRect(10, 20, 41, 20))
        self.checkBox_4 = QCheckBox(self.groupBox_31)
        self.checkBox_4.setObjectName(u"checkBox_4")
        self.checkBox_4.setEnabled(False)
        self.checkBox_4.setGeometry(QRect(90, 20, 71, 20))
        self.checkBox_5 = QCheckBox(self.groupBox_31)
        self.checkBox_5.setObjectName(u"checkBox_5")
        self.checkBox_5.setEnabled(False)
        self.checkBox_5.setGeometry(QRect(10, 40, 131, 20))
        self.groupBox_33 = QGroupBox(self.groupBox_32)
        self.groupBox_33.setObjectName(u"groupBox_33")
        self.groupBox_33.setGeometry(QRect(10, 280, 191, 131))
        self.groupBox_34 = QGroupBox(self.groupBox_33)
        self.groupBox_34.setObjectName(u"groupBox_34")
        self.groupBox_34.setEnabled(True)
        self.groupBox_34.setGeometry(QRect(10, 20, 171, 51))
        self.comboBox_activeLabels_Post = QComboBox(self.groupBox_34)
        self.comboBox_activeLabels_Post.setObjectName(u"comboBox_activeLabels_Post")
        self.comboBox_activeLabels_Post.setEnabled(True)
        self.comboBox_activeLabels_Post.setGeometry(QRect(10, 20, 151, 22))
        self.groupBox_35 = QGroupBox(self.groupBox_33)
        self.groupBox_35.setObjectName(u"groupBox_35")
        self.groupBox_35.setGeometry(QRect(10, 70, 171, 51))
        self.comboBox_paintOver_Post = QComboBox(self.groupBox_35)
        self.comboBox_paintOver_Post.setObjectName(u"comboBox_paintOver_Post")
        self.comboBox_paintOver_Post.setEnabled(True)
        self.comboBox_paintOver_Post.setGeometry(QRect(10, 20, 151, 22))
        self.checkBox_Segbrush_Post = QCheckBox(self.groupBox_32)
        self.checkBox_Segbrush_Post.setObjectName(u"checkBox_Segbrush_Post")
        self.checkBox_Segbrush_Post.setEnabled(True)
        self.checkBox_Segbrush_Post.setGeometry(QRect(50, 20, 101, 20))
        self.checkBox_Segbrush_Post.setChecked(False)
        self.tabWidget_2 = QTabWidget(self.PostSurgery)
        self.tabWidget_2.setObjectName(u"tabWidget_2")
        self.tabWidget_2.setEnabled(True)
        self.tabWidget_2.setGeometry(QRect(940, 570, 491, 211))
        self.tab_2 = QWidget()
        self.tab_2.setObjectName(u"tab_2")
        self.groupBox_10 = QGroupBox(self.tab_2)
        self.groupBox_10.setObjectName(u"groupBox_10")
        self.groupBox_10.setGeometry(QRect(10, 10, 281, 171))
        self.tableView_islands = QTableView(self.groupBox_10)
        self.tableView_islands.setObjectName(u"tableView_islands")
        self.tableView_islands.setEnabled(True)
        self.tableView_islands.setGeometry(QRect(10, 20, 261, 141))
        self.tableView_islands.setHorizontalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAsNeeded)
        self.tableView_islands.setEditTriggers(QAbstractItemView.EditTrigger.NoEditTriggers)
        self.tableView_islands.setSelectionMode(QAbstractItemView.SelectionMode.SingleSelection)
        self.tableView_islands.setSelectionBehavior(QAbstractItemView.SelectionBehavior.SelectRows)
        self.tableView_islands.horizontalHeader().setCascadingSectionResizes(False)
        self.label_11 = QLabel(self.tab_2)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(300, 20, 111, 16))
        self.label_11.setFont(font)
        self.label_12 = QLabel(self.tab_2)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(300, 50, 111, 16))
        self.label_12.setFont(font)
        self.spinBox_trio = QSpinBox(self.tab_2)
        self.spinBox_trio.setObjectName(u"spinBox_trio")
        self.spinBox_trio.setGeometry(QRect(420, 50, 42, 22))
        self.spinBox_trio.setButtonSymbols(QAbstractSpinBox.ButtonSymbols.NoButtons)
        self.spinBox_trio.setMinimum(1)
        self.spinBox_trio.setMaximum(180)
        self.spinBox_trio.setValue(3)
        self.spinBox_penta = QSpinBox(self.tab_2)
        self.spinBox_penta.setObjectName(u"spinBox_penta")
        self.spinBox_penta.setGeometry(QRect(420, 20, 42, 22))
        self.spinBox_penta.setButtonSymbols(QAbstractSpinBox.ButtonSymbols.NoButtons)
        self.spinBox_penta.setMinimum(1)
        self.spinBox_penta.setMaximum(180)
        self.spinBox_penta.setValue(5)
        self.tabWidget_2.addTab(self.tab_2, "")
        self.tab_3 = QWidget()
        self.tab_3.setObjectName(u"tab_3")
        self.tableView_activeBub_4 = QTableView(self.tab_3)
        self.tableView_activeBub_4.setObjectName(u"tableView_activeBub_4")
        self.tableView_activeBub_4.setEnabled(False)
        self.tableView_activeBub_4.setGeometry(QRect(10, 10, 181, 141))
        self.tableView_activeBub_4.setHorizontalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.tableView_activeBub_4.setEditTriggers(QAbstractItemView.EditTrigger.NoEditTriggers)
        self.tableView_activeBub_4.setSelectionMode(QAbstractItemView.SelectionMode.SingleSelection)
        self.tableView_activeBub_4.setSelectionBehavior(QAbstractItemView.SelectionBehavior.SelectRows)
        self.tableView_activeBub_4.horizontalHeader().setCascadingSectionResizes(False)
        self.label_6 = QLabel(self.tab_3)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(20, 200, 191, 61))
        self.textBrowser_4 = QTextBrowser(self.tab_3)
        self.textBrowser_4.setObjectName(u"textBrowser_4")
        self.textBrowser_4.setGeometry(QRect(200, 30, 141, 51))
        self.tabWidget_2.addTab(self.tab_3, "")
        self.tabWidget_3 = QTabWidget(self.PostSurgery)
        self.tabWidget_3.setObjectName(u"tabWidget_3")
        self.tabWidget_3.setGeometry(QRect(240, 570, 341, 211))
        self.tab_6 = QWidget()
        self.tab_6.setObjectName(u"tab_6")
        self.groupBox_26 = QGroupBox(self.tab_6)
        self.groupBox_26.setObjectName(u"groupBox_26")
        self.groupBox_26.setGeometry(QRect(0, 20, 121, 51))
        self.comboBox_timestamp = QComboBox(self.groupBox_26)
        self.comboBox_timestamp.addItem("")
        self.comboBox_timestamp.addItem("")
        self.comboBox_timestamp.addItem("")
        self.comboBox_timestamp.addItem("")
        self.comboBox_timestamp.addItem("")
        self.comboBox_timestamp.addItem("")
        self.comboBox_timestamp.addItem("")
        self.comboBox_timestamp.addItem("")
        self.comboBox_timestamp.addItem("")
        self.comboBox_timestamp.addItem("")
        self.comboBox_timestamp.addItem("")
        self.comboBox_timestamp.addItem("")
        self.comboBox_timestamp.addItem("")
        self.comboBox_timestamp.addItem("")
        self.comboBox_timestamp.addItem("")
        self.comboBox_timestamp.addItem("")
        self.comboBox_timestamp.setObjectName(u"comboBox_timestamp")
        self.comboBox_timestamp.setEnabled(True)
        self.comboBox_timestamp.setGeometry(QRect(10, 20, 101, 22))
        self.groupBox_27 = QGroupBox(self.tab_6)
        self.groupBox_27.setObjectName(u"groupBox_27")
        self.groupBox_27.setGeometry(QRect(130, 10, 201, 171))
        self.label_8 = QLabel(self.groupBox_27)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(10, 10, 111, 16))
        self.label_8.setFont(font)
        self.label_10 = QLabel(self.groupBox_27)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(10, 80, 111, 16))
        self.label_10.setFont(font)
        self.pushButton_reset_Post = QPushButton(self.groupBox_27)
        self.pushButton_reset_Post.setObjectName(u"pushButton_reset_Post")
        self.pushButton_reset_Post.setGeometry(QRect(10, 140, 75, 24))
        self.pushButton_auto_Post = QPushButton(self.groupBox_27)
        self.pushButton_auto_Post.setObjectName(u"pushButton_auto_Post")
        self.pushButton_auto_Post.setGeometry(QRect(100, 140, 75, 24))
        self.display_window_Post = QLCDNumber(self.groupBox_27)
        self.display_window_Post.setObjectName(u"display_window_Post")
        self.display_window_Post.setGeometry(QRect(140, 0, 41, 31))
        self.display_window_Post.setMaximumSize(QSize(16777215, 100))
        self.display_window_Post.setAutoFillBackground(False)
        self.display_window_Post.setStyleSheet(u"color: rgb(0, 0, 0); background-color: white;")
        self.display_level_Post = QLCDNumber(self.groupBox_27)
        self.display_level_Post.setObjectName(u"display_level_Post")
        self.display_level_Post.setGeometry(QRect(140, 70, 41, 31))
        self.display_level_Post.setMaximumSize(QSize(16777215, 100))
        self.display_level_Post.setAutoFillBackground(False)
        self.display_level_Post.setStyleSheet(u"color: rgb(0, 0, 0); background-color: white;")
        self.changeContrast_Post = QSlider(self.groupBox_27)
        self.changeContrast_Post.setObjectName(u"changeContrast_Post")
        self.changeContrast_Post.setGeometry(QRect(20, 40, 151, 22))
        self.changeContrast_Post.setStyleSheet(u"")
        self.changeContrast_Post.setMaximum(99)
        self.changeContrast_Post.setSingleStep(1)
        self.changeContrast_Post.setPageStep(10)
        self.changeContrast_Post.setValue(0)
        self.changeContrast_Post.setOrientation(Qt.Orientation.Horizontal)
        self.changeBrightness_Post = QSlider(self.groupBox_27)
        self.changeBrightness_Post.setObjectName(u"changeBrightness_Post")
        self.changeBrightness_Post.setGeometry(QRect(20, 110, 151, 22))
        self.changeBrightness_Post.setMaximum(99)
        self.changeBrightness_Post.setSingleStep(1)
        self.changeBrightness_Post.setPageStep(10)
        self.changeBrightness_Post.setValue(0)
        self.changeBrightness_Post.setOrientation(Qt.Orientation.Horizontal)
        self.tabWidget_3.addTab(self.tab_6, "")
        self.tab_7 = QWidget()
        self.tab_7.setObjectName(u"tab_7")
        self.tabWidget_3.addTab(self.tab_7, "")
        self.tab_8 = QWidget()
        self.tab_8.setObjectName(u"tab_8")
        self.tabWidget_3.addTab(self.tab_8, "")
        self.tab_9 = QWidget()
        self.tab_9.setObjectName(u"tab_9")
        self.tabWidget_3.addTab(self.tab_9, "")
        self.groupBox_37 = QGroupBox(self.PostSurgery)
        self.groupBox_37.setObjectName(u"groupBox_37")
        self.groupBox_37.setGeometry(QRect(20, 30, 541, 531))
        self.frame_8 = QFrame(self.groupBox_37)
        self.frame_8.setObjectName(u"frame_8")
        self.frame_8.setGeometry(QRect(0, 20, 261, 171))
        self.frame_8.setStyleSheet(u"border-color: rgb(170, 170, 170);\n"
"background-color: rgb(131, 131, 131);")
        self.frame_8.setFrameShape(QFrame.Shape.StyledPanel)
        self.frame_8.setFrameShadow(QFrame.Shadow.Raised)
        self.vtkWidget_coronal_Post = QVTKRenderWindowInteractor(self.frame_8)
        self.vtkWidget_coronal_Post.setObjectName(u"vtkWidget_coronal_Post")
        self.vtkWidget_coronal_Post.setGeometry(QRect(10, 10, 231, 141))
        self.vtkWidget_coronal_Post.setStyleSheet(u"background-color: rgb(200, 177, 176);")
        self.fit_to_zoom_coronal_Post = QPushButton(self.frame_8)
        self.fit_to_zoom_coronal_Post.setObjectName(u"fit_to_zoom_coronal_Post")
        self.fit_to_zoom_coronal_Post.setGeometry(QRect(10, 150, 81, 21))
        self.fit_to_zoom_coronal_Post.setStyleSheet(u"\n"
"background-color: rgb(0, 153, 255);")
        self.fit_to_zoom_coronal_Post.setAutoDefault(False)
        self.fit_to_zoom_coronal_Post.setFlat(False)
        self.zoom_in_coronal_Post = QToolButton(self.frame_8)
        self.zoom_in_coronal_Post.setObjectName(u"zoom_in_coronal_Post")
        self.zoom_in_coronal_Post.setGeometry(QRect(90, 150, 22, 22))
        self.zoom_out_coronal_Post = QToolButton(self.frame_8)
        self.zoom_out_coronal_Post.setObjectName(u"zoom_out_coronal_Post")
        self.zoom_out_coronal_Post.setGeometry(QRect(110, 150, 22, 22))
        self.Scroll_coronal_Post = QScrollBar(self.frame_8)
        self.Scroll_coronal_Post.setObjectName(u"Scroll_coronal_Post")
        self.Scroll_coronal_Post.setGeometry(QRect(240, 10, 16, 141))
        self.Scroll_coronal_Post.setOrientation(Qt.Orientation.Vertical)
        self.frame_7 = QFrame(self.groupBox_37)
        self.frame_7.setObjectName(u"frame_7")
        self.frame_7.setGeometry(QRect(270, 20, 261, 171))
        self.frame_7.setStyleSheet(u"border-color: rgb(170, 170, 170);\n"
"background-color: rgb(131, 131, 131);\n"
"\n"
"")
        self.frame_7.setFrameShape(QFrame.Shape.StyledPanel)
        self.frame_7.setFrameShadow(QFrame.Shadow.Raised)
        self.fit_to_zoom_sagittal_Post = QPushButton(self.frame_7)
        self.fit_to_zoom_sagittal_Post.setObjectName(u"fit_to_zoom_sagittal_Post")
        self.fit_to_zoom_sagittal_Post.setGeometry(QRect(10, 150, 81, 21))
        self.fit_to_zoom_sagittal_Post.setStyleSheet(u"\n"
"background-color: rgb(0, 153, 255);")
        self.fit_to_zoom_sagittal_Post.setAutoDefault(False)
        self.fit_to_zoom_sagittal_Post.setFlat(False)
        self.zoom_out_sagittal_Post = QToolButton(self.frame_7)
        self.zoom_out_sagittal_Post.setObjectName(u"zoom_out_sagittal_Post")
        self.zoom_out_sagittal_Post.setGeometry(QRect(110, 150, 22, 22))
        self.zoom_in_sagittal_Post = QToolButton(self.frame_7)
        self.zoom_in_sagittal_Post.setObjectName(u"zoom_in_sagittal_Post")
        self.zoom_in_sagittal_Post.setGeometry(QRect(90, 150, 22, 22))
        self.Scroll_sagittal_Post = QScrollBar(self.frame_7)
        self.Scroll_sagittal_Post.setObjectName(u"Scroll_sagittal_Post")
        self.Scroll_sagittal_Post.setGeometry(QRect(240, 10, 16, 141))
        self.Scroll_sagittal_Post.setOrientation(Qt.Orientation.Vertical)
        self.vtkWidget_sagittal_Post = QVTKRenderWindowInteractor(self.frame_7)
        self.vtkWidget_sagittal_Post.setObjectName(u"vtkWidget_sagittal_Post")
        self.vtkWidget_sagittal_Post.setGeometry(QRect(10, 10, 231, 141))
        self.vtkWidget_sagittal_Post.setStyleSheet(u"background-color: rgb(200, 177, 176);")
        self.frame_3 = QFrame(self.groupBox_37)
        self.frame_3.setObjectName(u"frame_3")
        self.frame_3.setGeometry(QRect(0, 200, 531, 321))
        self.frame_3.setStyleSheet(u"border-color: rgb(170, 170, 170);\n"
"background-color: rgb(131, 131, 131);\n"
"")
        self.frame_3.setFrameShape(QFrame.Shape.StyledPanel)
        self.frame_3.setFrameShadow(QFrame.Shadow.Raised)
        self.fit_to_zoom_axial_Post = QPushButton(self.frame_3)
        self.fit_to_zoom_axial_Post.setObjectName(u"fit_to_zoom_axial_Post")
        self.fit_to_zoom_axial_Post.setGeometry(QRect(10, 300, 81, 21))
        self.fit_to_zoom_axial_Post.setStyleSheet(u"\n"
"background-color: rgb(0, 153, 255);")
        self.fit_to_zoom_axial_Post.setAutoDefault(False)
        self.fit_to_zoom_axial_Post.setFlat(False)
        self.zoom_in_axial_Post = QToolButton(self.frame_3)
        self.zoom_in_axial_Post.setObjectName(u"zoom_in_axial_Post")
        self.zoom_in_axial_Post.setGeometry(QRect(90, 300, 22, 22))
        self.zoom_out_axial_Post = QToolButton(self.frame_3)
        self.zoom_out_axial_Post.setObjectName(u"zoom_out_axial_Post")
        self.zoom_out_axial_Post.setGeometry(QRect(110, 300, 22, 22))
        self.Scroll_axial_Post = QScrollBar(self.frame_3)
        self.Scroll_axial_Post.setObjectName(u"Scroll_axial_Post")
        self.Scroll_axial_Post.setGeometry(QRect(510, 10, 16, 291))
        self.Scroll_axial_Post.setOrientation(Qt.Orientation.Vertical)
        self.vtkWidget_axial_Post = QVTKRenderWindowInteractor(self.frame_3)
        self.vtkWidget_axial_Post.setObjectName(u"vtkWidget_axial_Post")
        self.vtkWidget_axial_Post.setGeometry(QRect(10, 10, 501, 291))
        self.vtkWidget_axial_Post.setStyleSheet(u"background-color: rgb(200, 177, 176);")
        self.groupBox_38 = QGroupBox(self.PostSurgery)
        self.groupBox_38.setObjectName(u"groupBox_38")
        self.groupBox_38.setGeometry(QRect(590, 30, 541, 531))
        self.frame_15 = QFrame(self.groupBox_38)
        self.frame_15.setObjectName(u"frame_15")
        self.frame_15.setGeometry(QRect(0, 20, 261, 171))
        self.frame_15.setStyleSheet(u"border-color: rgb(170, 170, 170);\n"
"background-color: rgb(131, 131, 131);")
        self.frame_15.setFrameShape(QFrame.Shape.StyledPanel)
        self.frame_15.setFrameShadow(QFrame.Shadow.Raised)
        self.vtkWidget_coronal_Post_4 = QVTKRenderWindowInteractor(self.frame_15)
        self.vtkWidget_coronal_Post_4.setObjectName(u"vtkWidget_coronal_Post_4")
        self.vtkWidget_coronal_Post_4.setGeometry(QRect(10, 10, 231, 141))
        self.vtkWidget_coronal_Post_4.setStyleSheet(u"background-color: rgb(200, 177, 176);")
        self.fit_to_zoom_coronal_Post_4 = QPushButton(self.frame_15)
        self.fit_to_zoom_coronal_Post_4.setObjectName(u"fit_to_zoom_coronal_Post_4")
        self.fit_to_zoom_coronal_Post_4.setGeometry(QRect(10, 150, 81, 21))
        self.fit_to_zoom_coronal_Post_4.setStyleSheet(u"\n"
"background-color: rgb(0, 153, 255);")
        self.fit_to_zoom_coronal_Post_4.setAutoDefault(False)
        self.fit_to_zoom_coronal_Post_4.setFlat(False)
        self.zoom_in_coronal_Post_4 = QToolButton(self.frame_15)
        self.zoom_in_coronal_Post_4.setObjectName(u"zoom_in_coronal_Post_4")
        self.zoom_in_coronal_Post_4.setGeometry(QRect(90, 150, 22, 22))
        self.zoom_out_coronal_Post_4 = QToolButton(self.frame_15)
        self.zoom_out_coronal_Post_4.setObjectName(u"zoom_out_coronal_Post_4")
        self.zoom_out_coronal_Post_4.setGeometry(QRect(110, 150, 22, 22))
        self.Scroll_coronal_Post_4 = QScrollBar(self.frame_15)
        self.Scroll_coronal_Post_4.setObjectName(u"Scroll_coronal_Post_4")
        self.Scroll_coronal_Post_4.setGeometry(QRect(240, 10, 16, 141))
        self.Scroll_coronal_Post_4.setOrientation(Qt.Orientation.Vertical)
        self.frame_16 = QFrame(self.groupBox_38)
        self.frame_16.setObjectName(u"frame_16")
        self.frame_16.setGeometry(QRect(270, 20, 261, 171))
        self.frame_16.setStyleSheet(u"border-color: rgb(170, 170, 170);\n"
"background-color: rgb(131, 131, 131);\n"
"\n"
"")
        self.frame_16.setFrameShape(QFrame.Shape.StyledPanel)
        self.frame_16.setFrameShadow(QFrame.Shadow.Raised)
        self.fit_to_zoom_sagittal_Post_4 = QPushButton(self.frame_16)
        self.fit_to_zoom_sagittal_Post_4.setObjectName(u"fit_to_zoom_sagittal_Post_4")
        self.fit_to_zoom_sagittal_Post_4.setGeometry(QRect(10, 150, 81, 21))
        self.fit_to_zoom_sagittal_Post_4.setStyleSheet(u"\n"
"background-color: rgb(0, 153, 255);")
        self.fit_to_zoom_sagittal_Post_4.setAutoDefault(False)
        self.fit_to_zoom_sagittal_Post_4.setFlat(False)
        self.zoom_out_sagittal_Post_4 = QToolButton(self.frame_16)
        self.zoom_out_sagittal_Post_4.setObjectName(u"zoom_out_sagittal_Post_4")
        self.zoom_out_sagittal_Post_4.setGeometry(QRect(110, 150, 22, 22))
        self.zoom_in_sagittal_Post_4 = QToolButton(self.frame_16)
        self.zoom_in_sagittal_Post_4.setObjectName(u"zoom_in_sagittal_Post_4")
        self.zoom_in_sagittal_Post_4.setGeometry(QRect(90, 150, 22, 22))
        self.Scroll_sagittal_Post_4 = QScrollBar(self.frame_16)
        self.Scroll_sagittal_Post_4.setObjectName(u"Scroll_sagittal_Post_4")
        self.Scroll_sagittal_Post_4.setGeometry(QRect(240, 10, 16, 141))
        self.Scroll_sagittal_Post_4.setOrientation(Qt.Orientation.Vertical)
        self.vtkWidget_sagittal_Post_4 = QVTKRenderWindowInteractor(self.frame_16)
        self.vtkWidget_sagittal_Post_4.setObjectName(u"vtkWidget_sagittal_Post_4")
        self.vtkWidget_sagittal_Post_4.setGeometry(QRect(10, 10, 231, 141))
        self.vtkWidget_sagittal_Post_4.setStyleSheet(u"background-color: rgb(200, 177, 176);")
        self.frame_17 = QFrame(self.groupBox_38)
        self.frame_17.setObjectName(u"frame_17")
        self.frame_17.setGeometry(QRect(0, 200, 531, 321))
        self.frame_17.setStyleSheet(u"border-color: rgb(170, 170, 170);\n"
"background-color: rgb(131, 131, 131);\n"
"")
        self.frame_17.setFrameShape(QFrame.Shape.StyledPanel)
        self.frame_17.setFrameShadow(QFrame.Shadow.Raised)
        self.fit_to_zoom_axial_Post_4 = QPushButton(self.frame_17)
        self.fit_to_zoom_axial_Post_4.setObjectName(u"fit_to_zoom_axial_Post_4")
        self.fit_to_zoom_axial_Post_4.setGeometry(QRect(10, 300, 81, 21))
        self.fit_to_zoom_axial_Post_4.setStyleSheet(u"\n"
"background-color: rgb(0, 153, 255);")
        self.fit_to_zoom_axial_Post_4.setAutoDefault(False)
        self.fit_to_zoom_axial_Post_4.setFlat(False)
        self.zoom_in_axial_Post_4 = QToolButton(self.frame_17)
        self.zoom_in_axial_Post_4.setObjectName(u"zoom_in_axial_Post_4")
        self.zoom_in_axial_Post_4.setGeometry(QRect(90, 300, 22, 22))
        self.zoom_out_axial_Post_4 = QToolButton(self.frame_17)
        self.zoom_out_axial_Post_4.setObjectName(u"zoom_out_axial_Post_4")
        self.zoom_out_axial_Post_4.setGeometry(QRect(110, 300, 22, 22))
        self.Scroll_axial_Post_4 = QScrollBar(self.frame_17)
        self.Scroll_axial_Post_4.setObjectName(u"Scroll_axial_Post_4")
        self.Scroll_axial_Post_4.setGeometry(QRect(510, 10, 16, 291))
        self.Scroll_axial_Post_4.setOrientation(Qt.Orientation.Vertical)
        self.vtkWidget_axial_Post_4 = QVTKRenderWindowInteractor(self.frame_17)
        self.vtkWidget_axial_Post_4.setObjectName(u"vtkWidget_axial_Post_4")
        self.vtkWidget_axial_Post_4.setGeometry(QRect(10, 10, 501, 291))
        self.vtkWidget_axial_Post_4.setStyleSheet(u"background-color: rgb(200, 177, 176);")
        self.groupBox_36 = QGroupBox(self.PostSurgery)
        self.groupBox_36.setObjectName(u"groupBox_36")
        self.groupBox_36.setGeometry(QRect(600, 570, 311, 221))
        self.groupBox_47 = QGroupBox(self.groupBox_36)
        self.groupBox_47.setObjectName(u"groupBox_47")
        self.groupBox_47.setGeometry(QRect(10, 20, 121, 51))
        self.histogram_image = QComboBox(self.groupBox_47)
        self.histogram_image.addItem("")
        self.histogram_image.addItem("")
        self.histogram_image.addItem("")
        self.histogram_image.addItem("")
        self.histogram_image.setObjectName(u"histogram_image")
        self.histogram_image.setEnabled(True)
        self.histogram_image.setGeometry(QRect(10, 20, 101, 22))
        self.groupBox_48 = QGroupBox(self.groupBox_36)
        self.groupBox_48.setObjectName(u"groupBox_48")
        self.groupBox_48.setGeometry(QRect(160, 20, 121, 51))
        self.histogram_label = QComboBox(self.groupBox_48)
        self.histogram_label.setObjectName(u"histogram_label")
        self.histogram_label.setEnabled(True)
        self.histogram_label.setGeometry(QRect(10, 20, 101, 22))
        self.widget_histogram = PlotWidget(self.groupBox_36)
        self.widget_histogram.setObjectName(u"widget_histogram")
        self.widget_histogram.setGeometry(QRect(10, 100, 291, 101))
        self.pushButton = QPushButton(self.PostSurgery)
        self.pushButton.setObjectName(u"pushButton")
        self.pushButton.setEnabled(False)
        self.pushButton.setGeometry(QRect(1310, 540, 121, 41))
        self.tabWidget.addTab(self.PostSurgery, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 1719, 22))
        self.menuGUI = QMenu(self.menubar)
        self.menuGUI.setObjectName(u"menuGUI")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.menubar.addAction(self.menuGUI.menuAction())

        self.retranslateUi(MainWindow)

        self.tabWidget.setCurrentIndex(0)
        self.toolbar.setCurrentIndex(0)
        self.stackedWidget.setCurrentIndex(0)
        self.comboBox_activeLabels.setCurrentIndex(-1)
        self.fit_to_zoom_axial.setDefault(False)
        self.fit_to_zoom_sagittal.setDefault(False)
        self.fit_to_zoom_coronal.setDefault(False)
        self.comboBox_3.setCurrentIndex(0)
        self.comboBox_activeLabels_Post.setCurrentIndex(-1)
        self.tabWidget_2.setCurrentIndex(0)
        self.tabWidget_3.setCurrentIndex(0)
        self.comboBox_timestamp.setCurrentIndex(0)
        self.fit_to_zoom_coronal_Post.setDefault(False)
        self.fit_to_zoom_sagittal_Post.setDefault(False)
        self.fit_to_zoom_axial_Post.setDefault(False)
        self.fit_to_zoom_coronal_Post_4.setDefault(False)
        self.fit_to_zoom_sagittal_Post_4.setDefault(False)
        self.fit_to_zoom_axial_Post_4.setDefault(False)
        self.histogram_image.setCurrentIndex(0)
        self.histogram_label.setCurrentIndex(-1)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
#if QT_CONFIG(accessibility)
        MainWindow.setAccessibleName("")
#endif // QT_CONFIG(accessibility)
#if QT_CONFIG(tooltip)
        self.PreSurgery.setToolTip(QCoreApplication.translate("MainWindow", u"<html><head/><body><p>Pre</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(tooltip)
        self.toolbar.setToolTip("")
#endif // QT_CONFIG(tooltip)
        self.groupBox_8.setTitle("")
        self.label_7.setText(QCoreApplication.translate("MainWindow", u"Contrast / Window", None))
        self.label_9.setText(QCoreApplication.translate("MainWindow", u"Brightness / Level", None))
        self.pushButton_reset.setText(QCoreApplication.translate("MainWindow", u"Reset", None))
        self.pushButton_auto.setText(QCoreApplication.translate("MainWindow", u"Auto", None))
#if QT_CONFIG(tooltip)
        self.toolButton_LoadFile.setToolTip(QCoreApplication.translate("MainWindow", u"Load File", None))
#endif // QT_CONFIG(tooltip)
        self.toolButton_LoadFile.setText(QCoreApplication.translate("MainWindow", u"...", None))
#if QT_CONFIG(tooltip)
        self.toolButton_ExportFile.setToolTip(QCoreApplication.translate("MainWindow", u"Export File", None))
#endif // QT_CONFIG(tooltip)
        self.toolButton_ExportFile.setText(QCoreApplication.translate("MainWindow", u"...", None))
        self.toolbar.setTabText(self.toolbar.indexOf(self.File), "")
#if QT_CONFIG(tooltip)
        self.toolbar.setTabToolTip(self.toolbar.indexOf(self.File), QCoreApplication.translate("MainWindow", u"File Setup", None))
#endif // QT_CONFIG(tooltip)
        self.checkBox_threshold.setText(QCoreApplication.translate("MainWindow", u"Threshold ON", None))
        self.groupBox_2.setTitle(QCoreApplication.translate("MainWindow", u"THRESHOLD", None))
        self.radioButton_bounded.setText(QCoreApplication.translate("MainWindow", u"Bounded", None))
        self.radioButton_lower.setText(QCoreApplication.translate("MainWindow", u"Lower-Only", None))
        self.radioButton_upper.setText(QCoreApplication.translate("MainWindow", u"Upper-Only", None))
        self.groupBox_12.setTitle(QCoreApplication.translate("MainWindow", u"Lower Threshold", None))
        self.groupBox_21.setTitle(QCoreApplication.translate("MainWindow", u"Upper Threshold", None))
        self.pushButton_3.setText(QCoreApplication.translate("MainWindow", u"Back", None))
        self.pushButton_Next1.setText(QCoreApplication.translate("MainWindow", u"Next", None))
        self.textBrowser.setHtml(QCoreApplication.translate("MainWindow", u"<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:'Segoe UI'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">Step 1/3<br /></span><span style=\" font-size:10pt; font-weight:700;\">Presegmentation</span></p></body></html>", None))
        self.pushButton_addBubbles.setText(QCoreApplication.translate("MainWindow", u"Add Bubble at Cursor", None))
        self.groupBox_4.setTitle(QCoreApplication.translate("MainWindow", u"Bubble Radius", None))
        self.pushButton_delete.setText(QCoreApplication.translate("MainWindow", u"Delete Active Bubble", None))
        self.groupBox_5.setTitle(QCoreApplication.translate("MainWindow", u"Active Bubbles", None))
        self.textBrowser_2.setHtml(QCoreApplication.translate("MainWindow", u"<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:'Segoe UI'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">Step 2/3<br /></span><span style=\" font-size:10pt; font-weight:700;\">Initialization</span></p></body></html>", None))
        self.pushButton_Back2.setText(QCoreApplication.translate("MainWindow", u"Back", None))
        self.pushButton_Next2.setText(QCoreApplication.translate("MainWindow", u"Next", None))
        self.textBrowser_3.setHtml(QCoreApplication.translate("MainWindow", u"<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:'Segoe UI'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">Step 3/3<br /></span><span style=\" font-size:10pt; font-weight:700;\">Evolution</span></p></body></html>", None))
        self.pushButton_Back3.setText(QCoreApplication.translate("MainWindow", u"Back", None))
        self.pushButton_Finish.setText(QCoreApplication.translate("MainWindow", u"Finsish", None))
        self.toolButton_runEvo.setText(QCoreApplication.translate("MainWindow", u"...", None))
        self.toolButton_2.setText(QCoreApplication.translate("MainWindow", u"...", None))
        self.toolButton_3.setText(QCoreApplication.translate("MainWindow", u"...", None))
        self.groupBox_9.setTitle(QCoreApplication.translate("MainWindow", u"Step Size", None))
        self.groupBox_11.setTitle(QCoreApplication.translate("MainWindow", u"Iteration", None))
        self.toolbar.setTabText(self.toolbar.indexOf(self.tab), "")
#if QT_CONFIG(tooltip)
        self.toolbar.setTabToolTip(self.toolbar.indexOf(self.tab), QCoreApplication.translate("MainWindow", u"Semi-automatic Segmentation", None))
#endif // QT_CONFIG(tooltip)
        self.groupBox_13.setTitle(QCoreApplication.translate("MainWindow", u"Paintbrush Inspector", None))
        self.groupBox_14.setTitle(QCoreApplication.translate("MainWindow", u"Brush Style", None))
        self.paint_square.setText("")
        self.paint_round.setText("")
        self.paint_adjusted.setText("")
        self.groupBox_15.setTitle(QCoreApplication.translate("MainWindow", u"Brush Size", None))
        self.groupBox_17.setTitle(QCoreApplication.translate("MainWindow", u"Brush Options", None))
        self.brush_3d.setText(QCoreApplication.translate("MainWindow", u"3D", None))
        self.checkBox_2.setText(QCoreApplication.translate("MainWindow", u"Isotropic", None))
        self.checkBox_3.setText(QCoreApplication.translate("MainWindow", u"Cursor chases brush", None))
        self.groupBox_18.setTitle(QCoreApplication.translate("MainWindow", u"Segmentation Labels", None))
        self.groupBox_16.setTitle(QCoreApplication.translate("MainWindow", u"Active Labels", None))
        self.groupBox_19.setTitle(QCoreApplication.translate("MainWindow", u"Paint over", None))
        self.groupBox_20.setTitle(QCoreApplication.translate("MainWindow", u"Overall label opacity", None))
        self.toolbar.setTabText(self.toolbar.indexOf(self.tab_4), "")
#if QT_CONFIG(tooltip)
        self.toolbar.setTabToolTip(self.toolbar.indexOf(self.tab_4), QCoreApplication.translate("MainWindow", u"Paintbrush / manual Segmentation", None))
#endif // QT_CONFIG(tooltip)
        self.groupBox.setTitle(QCoreApplication.translate("MainWindow", u"Lambda Position", None))
        self.pushButton_2.setText(QCoreApplication.translate("MainWindow", u"Pick Position", None))
        self.groupBox_3.setTitle(QCoreApplication.translate("MainWindow", u"Bregma Position", None))
        self.pushButton_4.setText(QCoreApplication.translate("MainWindow", u"Pick Position", None))
        self.groupBox_22.setTitle(QCoreApplication.translate("MainWindow", u"Distance", None))
        self.toolbar.setTabText(self.toolbar.indexOf(self.tab_5), "")
        self.fit_to_zoom_axial.setText(QCoreApplication.translate("MainWindow", u"Fit-to-Zoom", None))
        self.zoom_in_axial.setText(QCoreApplication.translate("MainWindow", u"+", None))
        self.zoom_out_axial.setText(QCoreApplication.translate("MainWindow", u"-", None))
        self.fit_to_zoom_sagittal.setText(QCoreApplication.translate("MainWindow", u"Fit-to-Zoom", None))
        self.zoom_out_sagittal.setText(QCoreApplication.translate("MainWindow", u"-", None))
        self.zoom_in_sagittal.setText(QCoreApplication.translate("MainWindow", u"+", None))
        self.fit_to_zoom_coronal.setText(QCoreApplication.translate("MainWindow", u"Fit-to-Zoom", None))
        self.zoom_in_coronal.setText(QCoreApplication.translate("MainWindow", u"+", None))
        self.zoom_out_coronal.setText(QCoreApplication.translate("MainWindow", u"-", None))
        self.file_name_displayed.setHtml(QCoreApplication.translate("MainWindow", u"<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:'Segoe UI'; font-size:9pt; font-weight:700; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt; color:#ff0000;\">PLEASE LOAD FILE</span></p></body></html>", None))
        self.groupBox_6.setTitle(QCoreApplication.translate("MainWindow", u"Cursor position (x,y,z)", None))
        self.groupBox_7.setTitle(QCoreApplication.translate("MainWindow", u"Intensity under cursor", None))
        self.label_4.setText(QCoreApplication.translate("MainWindow", u"Original file", None))
        self.label_5.setText(QCoreApplication.translate("MainWindow", u"Segmentation Image", None))
        self.checkBox_measurement.setText(QCoreApplication.translate("MainWindow", u" OFF", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.PreSurgery), QCoreApplication.translate("MainWindow", u"PreSurgery", None))
#if QT_CONFIG(tooltip)
        self.toolButton_LoadFile_Post.setToolTip(QCoreApplication.translate("MainWindow", u"Load File", None))
#endif // QT_CONFIG(tooltip)
        self.toolButton_LoadFile_Post.setText(QCoreApplication.translate("MainWindow", u"...", None))
        self.groupBox_23.setTitle(QCoreApplication.translate("MainWindow", u"Change View / Data", None))
        self.comboBox_3.setItemText(0, QCoreApplication.translate("MainWindow", u"Coronal", None))
        self.comboBox_3.setItemText(1, QCoreApplication.translate("MainWindow", u"Sagittal", None))

        self.file_name_displayed_Post.setHtml(QCoreApplication.translate("MainWindow", u"<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:'Segoe UI'; font-size:9pt; font-weight:700; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt; color:#ff0000;\">PLEASE LOAD FILE</span></p></body></html>", None))
        self.groupBox_24.setTitle(QCoreApplication.translate("MainWindow", u"Cursor position (x,y,z)", None))
        self.groupBox_25.setTitle(QCoreApplication.translate("MainWindow", u"Intensity under cursor", None))
        self.groupBox_32.setTitle(QCoreApplication.translate("MainWindow", u"Segmentation Brush", None))
        self.groupBox_28.setTitle(QCoreApplication.translate("MainWindow", u"Paintbrush Inspector", None))
        self.groupBox_29.setTitle(QCoreApplication.translate("MainWindow", u"Brush Style", None))
        self.paint_square_Post.setText("")
        self.paint_round_Post.setText("")
        self.paint_adjusted_2.setText("")
        self.groupBox_30.setTitle(QCoreApplication.translate("MainWindow", u"Brush Size", None))
        self.groupBox_31.setTitle(QCoreApplication.translate("MainWindow", u"Brush Options", None))
        self.brush_3d_2.setText(QCoreApplication.translate("MainWindow", u"3D", None))
        self.checkBox_4.setText(QCoreApplication.translate("MainWindow", u"Isotropic", None))
        self.checkBox_5.setText(QCoreApplication.translate("MainWindow", u"Cursor chases brush", None))
        self.groupBox_33.setTitle(QCoreApplication.translate("MainWindow", u"Segmentation Labels", None))
        self.groupBox_34.setTitle(QCoreApplication.translate("MainWindow", u"Active Labels", None))
        self.groupBox_35.setTitle(QCoreApplication.translate("MainWindow", u"Paint over", None))
        self.checkBox_Segbrush_Post.setText(QCoreApplication.translate("MainWindow", u"Brush OFF", None))
        self.groupBox_10.setTitle(QCoreApplication.translate("MainWindow", u"Islands", None))
        self.label_11.setText(QCoreApplication.translate("MainWindow", u"Number of penta", None))
        self.label_12.setText(QCoreApplication.translate("MainWindow", u"Number of trio", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_2), QCoreApplication.translate("MainWindow", u"IONP-Islands", None))
        self.label_6.setText("")
        self.textBrowser_4.setHtml(QCoreApplication.translate("MainWindow", u"<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:'Segoe UI'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Each Label Color needs a brain region name!</p></body></html>", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_3), QCoreApplication.translate("MainWindow", u"Anatomy", None))
        self.groupBox_26.setTitle(QCoreApplication.translate("MainWindow", u"Timestamps", None))
        self.comboBox_timestamp.setItemText(0, QCoreApplication.translate("MainWindow", u"0", None))
        self.comboBox_timestamp.setItemText(1, QCoreApplication.translate("MainWindow", u"1", None))
        self.comboBox_timestamp.setItemText(2, QCoreApplication.translate("MainWindow", u"2", None))
        self.comboBox_timestamp.setItemText(3, QCoreApplication.translate("MainWindow", u"3", None))
        self.comboBox_timestamp.setItemText(4, QCoreApplication.translate("MainWindow", u"4", None))
        self.comboBox_timestamp.setItemText(5, QCoreApplication.translate("MainWindow", u"5", None))
        self.comboBox_timestamp.setItemText(6, QCoreApplication.translate("MainWindow", u"6", None))
        self.comboBox_timestamp.setItemText(7, QCoreApplication.translate("MainWindow", u"7", None))
        self.comboBox_timestamp.setItemText(8, QCoreApplication.translate("MainWindow", u"8", None))
        self.comboBox_timestamp.setItemText(9, QCoreApplication.translate("MainWindow", u"9", None))
        self.comboBox_timestamp.setItemText(10, QCoreApplication.translate("MainWindow", u"10", None))
        self.comboBox_timestamp.setItemText(11, QCoreApplication.translate("MainWindow", u"11", None))
        self.comboBox_timestamp.setItemText(12, QCoreApplication.translate("MainWindow", u"12", None))
        self.comboBox_timestamp.setItemText(13, QCoreApplication.translate("MainWindow", u"13", None))
        self.comboBox_timestamp.setItemText(14, QCoreApplication.translate("MainWindow", u"14", None))
        self.comboBox_timestamp.setItemText(15, QCoreApplication.translate("MainWindow", u"15", None))

        self.groupBox_27.setTitle("")
        self.label_8.setText(QCoreApplication.translate("MainWindow", u"Contrast / Window", None))
        self.label_10.setText(QCoreApplication.translate("MainWindow", u"Brightness / Level", None))
        self.pushButton_reset_Post.setText(QCoreApplication.translate("MainWindow", u"Reset", None))
        self.pushButton_auto_Post.setText(QCoreApplication.translate("MainWindow", u"Auto", None))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_6), QCoreApplication.translate("MainWindow", u"Image1", None))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_7), QCoreApplication.translate("MainWindow", u"Image2", None))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_8), QCoreApplication.translate("MainWindow", u"Image3", None))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_9), QCoreApplication.translate("MainWindow", u"Image4", None))
        self.groupBox_37.setTitle(QCoreApplication.translate("MainWindow", u"Image1", None))
        self.fit_to_zoom_coronal_Post.setText(QCoreApplication.translate("MainWindow", u"Fit-to-Zoom", None))
        self.zoom_in_coronal_Post.setText(QCoreApplication.translate("MainWindow", u"+", None))
        self.zoom_out_coronal_Post.setText(QCoreApplication.translate("MainWindow", u"-", None))
        self.fit_to_zoom_sagittal_Post.setText(QCoreApplication.translate("MainWindow", u"Fit-to-Zoom", None))
        self.zoom_out_sagittal_Post.setText(QCoreApplication.translate("MainWindow", u"-", None))
        self.zoom_in_sagittal_Post.setText(QCoreApplication.translate("MainWindow", u"+", None))
        self.fit_to_zoom_axial_Post.setText(QCoreApplication.translate("MainWindow", u"Fit-to-Zoom", None))
        self.zoom_in_axial_Post.setText(QCoreApplication.translate("MainWindow", u"+", None))
        self.zoom_out_axial_Post.setText(QCoreApplication.translate("MainWindow", u"-", None))
        self.groupBox_38.setTitle(QCoreApplication.translate("MainWindow", u"Image2", None))
        self.fit_to_zoom_coronal_Post_4.setText(QCoreApplication.translate("MainWindow", u"Fit-to-Zoom", None))
        self.zoom_in_coronal_Post_4.setText(QCoreApplication.translate("MainWindow", u"+", None))
        self.zoom_out_coronal_Post_4.setText(QCoreApplication.translate("MainWindow", u"-", None))
        self.fit_to_zoom_sagittal_Post_4.setText(QCoreApplication.translate("MainWindow", u"Fit-to-Zoom", None))
        self.zoom_out_sagittal_Post_4.setText(QCoreApplication.translate("MainWindow", u"-", None))
        self.zoom_in_sagittal_Post_4.setText(QCoreApplication.translate("MainWindow", u"+", None))
        self.fit_to_zoom_axial_Post_4.setText(QCoreApplication.translate("MainWindow", u"Fit-to-Zoom", None))
        self.zoom_in_axial_Post_4.setText(QCoreApplication.translate("MainWindow", u"+", None))
        self.zoom_out_axial_Post_4.setText(QCoreApplication.translate("MainWindow", u"-", None))
        self.groupBox_36.setTitle(QCoreApplication.translate("MainWindow", u"Histogram", None))
        self.groupBox_47.setTitle(QCoreApplication.translate("MainWindow", u"Image", None))
        self.histogram_image.setItemText(0, QCoreApplication.translate("MainWindow", u"1", None))
        self.histogram_image.setItemText(1, QCoreApplication.translate("MainWindow", u"2", None))
        self.histogram_image.setItemText(2, QCoreApplication.translate("MainWindow", u"3", None))
        self.histogram_image.setItemText(3, QCoreApplication.translate("MainWindow", u"4", None))

        self.groupBox_48.setTitle(QCoreApplication.translate("MainWindow", u"Label", None))
        self.pushButton.setText(QCoreApplication.translate("MainWindow", u"Generate Text File", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.PostSurgery), QCoreApplication.translate("MainWindow", u"PostSurgery", None))
        self.menuGUI.setTitle(QCoreApplication.translate("MainWindow", u"GUI", None))
    # retranslateUi

